title: The Giordani Family Blog
remote_theme: jekyll/minima

# Important for your /blog subfolder
url: "https://claudiogiordani.com"
baseurl: "/blog"

# GitHub Pages needs this specifically
plugins:
  - jekyll-remote-theme
