title: The Giordani Family Blog
theme: minima
remote_theme: jekyll/minima

# This tells GitHub where the blog lives
url: "https://claudiogiordani.com"
baseurl: "/blog"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
